# Generated by Django 4.1.6 on 2023-03-01 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('tags', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('expires_on', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
