# Generated by Django 3.2.7 on 2021-09-07 06:43

import users.models as user_model
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210902_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=user_model.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
