version: "3.7"

services:
  shulehub_api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - bridge
    environment:
      - RUN_TIME=production
      - DB_HOST=postgres

  postgres:
    restart: unless-stopped
    image: postgres:15
    networks:
      - bridge
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

networks:
  bridge:
    driver: bridge
