# Generated by Django 4.1.6 on 2023-03-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_extras', '0004_initial_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='school_extras.subject'),
        ),
    ]
