# Generated by Django 4.1.6 on 2023-03-06 07:57

import apps.schools.models
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('Bio', models.TextField(blank=True)),
                ('DP', models.CharField(blank=True, max_length=100, verbose_name='Display Picture')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', apps.schools.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
            },
        ),
    ]
