# Generated by Django 4.1.6 on 2023-03-06 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_extras', '0003_initial'),
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_extras.level'),
        ),
        migrations.AddField(
            model_name='groupregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupregistration',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_groups.studygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupregistration',
            unique_together={('student', 'study_group')},
        ),
    ]
